queries:
  - exclude: py/similar-function
  - exclude: py/empty-except
  - exclude: py/call-to-non-callable
  - include: py/undefined-placeholder-variable
  - include: py/uninitialized-local-variable
  - include: py/request-without-cert-validation
  - include: py/return-or-yield-outside-function
  - include: py/file-not-closed
  - include: py/exit-from-finally
  - include: py/ineffectual-statement
  - include: py/unused-global-variable
  - include: py/hardcoded-credentials
  - include: py/import-of-mutable-attribute
  - include: py/cyclic-import
  - include: py/unnecessary-lambda
  - include: py/print-during-import