[tool.black]
exclude = '''
/(
    venv
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
use_parentheses = true

[tool.mypy]
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true